### ISSUE TITLE
The Execute function in the task.py file is trying to convert a string to int() and then fails

### ISSUE THREAD

**Issue by ashwinterminator** [AndyCyberSec/pylovepdf#1]

**Comment by AndyBTuttofare** [comment]
I will try to reproduce the issue, which tool where you using?

**Comment by AndyCyberSec** [comment]
@ashwinterminator I will try to reproduce the issue, which tool where you using?

**Comment by ashwinterminator** [comment]
@AndyBTuttofare I was trying the Watermark tool.

The task.download() function also breaks later because there is a check for the status being 200.

The response from the iLovePDF guys has changed from 200 to TaskSuccess it would seem, hence the failures.

**Comment by ashwinterminator** [comment]
`    def execute(self):

        print('Uploading file...')
        self.upload()

        payload = self.process()

        response = self._send_request('post', 'process', payload, self.headers)

        print("File uploaded! Below file stats:")
        **self.status = int(response.status)**

        print(response)`

It fails once there.

`    def download(self):

        if len(self.files) > 0 and not self.debug and **self.status == 200:**

            print('Downloading processed file...')

            response = self._send_request('get', 'download/%s' % self.task, None, self.headers, False,
                                          None, stream=True)

            # file_ext = str(response.headers['content-type']).split('/')

            filename = self.clean_filename(re.search(r'(filename=\")(.+\.\w+)(\")',
                                                     str(response.headers['content-disposition'])).group(2))

            with open(self.download_path + '\\' + filename, 'wb') as f:
                for chunk in response.iter_content(10):
                    f.write(chunk)

            print('File downloaded!')

            return True

        else:
            print("no file to be downloaded")`

And here as well

Sorry if I am not being very helpful, I've never raised an issue on GitHub before :)

**Comment by AndyCyberSec** [comment]
@ashwinterminator Thank you! I am having some connection issue at my place today, I hope I can fix it tomorrow

**Comment by AndyCyberSec** [comment]
Now it should be fixed, thank you for your help :)
`pip install --upgrade pylovepdf`
